version: '3'
services:
  database-backup:
    # image: mysql:8.0
    build: .
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./script:/root/script
      - F:\药物警戒研究中心\59服务器数据备份\database-backup:/data/mysqlbak